//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Repositories.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Repositories.Scripts.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into departments (name, phone)
        ///values (@name, @phone)
        ///returning id.
        /// </summary>
        internal static string CreateDepartment {
            get {
                return ResourceManager.GetString("CreateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into employees (name, surname, phone, company_id, department_id)
        ///values (@name, @surname, @phone, @companyId, @departmentId) returning id.
        /// </summary>
        internal static string CreateEmployee {
            get {
                return ResourceManager.GetString("CreateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into passports (employee_id, type, number)
        ///values (@employeeId, @type, @number).
        /// </summary>
        internal static string CreatePassport {
            get {
                return ResourceManager.GetString("CreatePassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from departments
        ///where id = @id.
        /// </summary>
        internal static string DeleteDepartment {
            get {
                return ResourceManager.GetString("DeleteDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete
        ///from employees
        ///where id = @id returning id;.
        /// </summary>
        internal static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id, name, number
        ///from departments
        ///where id = @id.
        /// </summary>
        internal static string GetDepartmentById {
            get {
                return ResourceManager.GetString("GetDepartmentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    e.id,
        ///    e.name,
        ///    e.surname,
        ///    e.phone,
        ///    e.company_id as &quot;CompanyId&quot;,
        ///    e.department_id as &quot;DepartmentId&quot;,
        ///    p.type as &quot;PassportType&quot;,
        ///    p.number as &quot;PassportNumber&quot;
        ///from employees e
        ///left join passports p on e.department_id = p.id
        ///where e.id = @id.
        /// </summary>
        internal static string GetEmployeeById {
            get {
                return ResourceManager.GetString("GetEmployeeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    e.id, e.name, e.surname, e.phone, e.company_id,
        ///    p.type as &quot;PassportType&quot;, p.number as &quot;PassportNumber&quot;,
        ///    d.name as &quot;DepartmentName&quot;, d.phone as &quot;DepartmentPhone&quot;
        ///from employees e
        ///         left join passports p on e.id = p.employee_id
        ///         left join departments d on e.department_id = d.id
        ///where e.company_id = @companyId.
        /// </summary>
        internal static string GetEmployeesByCompany {
            get {
                return ResourceManager.GetString("GetEmployeesByCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    e.id,
        ///    e.name,
        ///    e.surname,
        ///    e.phone,
        ///    e.company_id,
        ///    p.type as &quot;PassportType&quot;,
        ///    p.number as &quot;PassportNumber&quot;,
        ///    d.name as &quot;DepartmentName&quot;,
        ///    d.phone as &quot;DepartmentPhone&quot;
        ///from employees e
        ///         left join passports p on e.id = p.employee_id
        ///         left join departments d on e.department_id = d.id
        ///where e.department_id = @departmentId;
        ///.
        /// </summary>
        internal static string GetEmployeesByDepartment {
            get {
                return ResourceManager.GetString("GetEmployeesByDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select exists(select id 
        ///              from departments
        ///              where id = @id).
        /// </summary>
        internal static string IsDepartmentExistById {
            get {
                return ResourceManager.GetString("IsDepartmentExistById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select exists(select id
        ///              from departments
        ///              where phone = @phone).
        /// </summary>
        internal static string isDepartmentExistByPhone {
            get {
                return ResourceManager.GetString("isDepartmentExistByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select exists(select id
        ///              from employees
        ///              where id = @id).
        /// </summary>
        internal static string IsEmployeeExistById {
            get {
                return ResourceManager.GetString("IsEmployeeExistById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select exists(select id
        ///              from employees
        ///              where phone = @phone).
        /// </summary>
        internal static string IsEmployeeExistByPhone {
            get {
                return ResourceManager.GetString("IsEmployeeExistByPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update departments
        ///set name = coalesce(@name, name),
        ///    phone = coalesce(@phone, phone)
        ///where id = @id.
        /// </summary>
        internal static string UpdateDepartment {
            get {
                return ResourceManager.GetString("UpdateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update employees
        ///set name = coalesce(@name, name),
        ///    surname = coalesce(@surname, surname),
        ///    phone = coalesce(@phone, phone),
        ///    company_id = coalesce(@companyId, company_id),
        ///    department_id = coalesce(@departmentId, department_id)
        ///where id = @id.
        /// </summary>
        internal static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update passports
        ///set type = coalesce(@type, type),
        ///    number = coalesce(@number, number)
        ///where employee_id = @employeeId.
        /// </summary>
        internal static string UpdatePassport {
            get {
                return ResourceManager.GetString("UpdatePassport", resourceCulture);
            }
        }
    }
}
